- hosts: localhost
  roles:
  - role: gitlab
    vars:
      gitlab_url: "{{ all_services_details.gitlab.url }}"
      gitea_username: "{{ all_services_details.gitlab.username }}"
      gitea_password: "{{ all_services_details.gitlab.password }}"

      ploigos_service_account:
        first_name: Ploigos
        last_name: ServiceAccount
        username: ploigos
        password: password123
        email: ploigos@example.com